### PR TITLE
Fix `ReduceLROnPlateau` scheduler for all regressors and classifiers

### LINKED ISSUE #109: Fix 'ReduceLROnPlateau' has no attribute 'get_last_lr'
This scheduler doesn't have this attributte because it doesn't inherit from `_LRScheduler`, and simply implementes the generic 'object' class.

Instead of getting the leanring rate with `get_last_lr`, we could fetch it with `optimizer.param_groups[0]['lr']` for this very specific case.

### PR DESCRIPTION
**Pull request by SarthakJariwala**
Fixes #109

### CODE REVIEW

**Comment by SarthakJariwala** [comment]
@xuyxu I've implemented fixes for all classifiers and regressors except SnapShot one (since its automatically set there)

**Comment by xuyxu** [comment]
Thanks for your great work @SarthakJariwala!

Kind of busy these days, and I will take a look in a few days.

**Review by xuyxu — COMMENTED** [review]
LGTM.

**Comment by xuyxu** [comment]
@all-contributors please add @SarthakJariwala for code, test

**Comment by xuyxu** [comment]
Merged, thanks for your nice code!

**Pull request merged**
